# Use Alpine Linux as the base image
FROM alpine:latest

ARG FOLDER_TO_COPY
ENV FOLDER_TO_COPY=${FOLDER_TO_COPY}

# Install vsftpd
RUN apk add --no-cache vsftpd

# Create a directory for anonymous users
RUN mkdir -p /var/ftp/pub
RUN mkdir -p /tmp


COPY ./ftp-honeypot/prompts_direct /tmp/prompts_direct
COPY ./ftp-honeypot/prompts_indirect /tmp/prompts_indirect

RUN if [ "$FOLDER_TO_COPY" = "prompts_direct" ]; then \
      cp /tmp/prompts_direct/* /var/ftp/pub/; \
    elif [ "$FOLDER_TO_COPY" = "prompts_indirect" ]; then \
      cp /tmp/prompts_indirect/* /var/ftp/pub/; \
    else \
      echo "No valid folder specified, copying default folder."; \
      cp /tmp/prompts_direct/* /var/ftp/pub/; \
    fi

RUN chown nobody:nogroup /var/ftp/pub

# Allow anonymous login
ADD vsftpd.conf vsftpd.conf
COPY vsftpd.conf /etc/vsftpd/vsftpd.conf

# Expose the FTP port
EXPOSE 21 21100-21110

ENTRYPOINT vsftpd /etc/vsftpd/vsftpd.conf && bash