FROM python:3

RUN apt update && apt install -y openssh-server
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN sed -i 's/#PermitTTY yes/PermitTTY yes/' /etc/ssh/sshd_config

# Set root password (change 'rootpassword' to your desired password)
RUN echo "root:root" | chpasswd

EXPOSE 22

ADD server.py server.py
EXPOSE 80
ENTRYPOINT service ssh start & python3 server.py