services:
  kali:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile-Kali
    container_name: kali_linux
    networks:
      hacking_net:
        ipv4_address: 192.168.100.5
    tty: true
    stdin_open: true

  poem_honey:
    build:
      context: ./poemhoney
      dockerfile: Dockerfile-PoemHoney
    container_name: poem_honey
    networks:
      hacking_net:
        ipv4_address: 192.168.100.8
    tty: true
    stdin_open: true

networks:
  hacking_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
